### ISSUE TITLE
click handler error on mobile

### ISSUE THREAD

**Issue by otrajman** [asah/zulip#7]
In mobile view when changing streams (I saw it from one PM to another PM), I believe the stream view is hidden before the observer code, causing the node to vanish and I get this (benign) error:

click_handlers.js:598 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at Object.onShow (click_handlers.js:598:26)
    at Object.show (tippy.esm.js:1386:24)
    at tippy.esm.js:1237:18

![image](https://user-images.githubusercontent.com/128812/153664092-191e735a-dbfd-4351-8fed-ee18852bc432.png)

**Comment by otrajman** [comment]
![image](https://user-images.githubusercontent.com/128812/153664053-2043debd-e1d8-4a6a-8f61-b53ded7d08a3.png)
